### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by bettywolfy** [Gatete/GMEAnniversary#6]
how to download GMS1?

i have the GMS2, but not the GMS1...

**Comment by MorsGames** [comment]
If you own a license for GMS1 then you can download it and find your license key from YoyoGames's website.
https://accounts.yoyogames.com/dashboard

If you don't already own a GMS1 license then you're in a bit of a difficult situation because there's no way to obtain one legally anymore. There might other ways, but we can't offer you support for those.
